### ISSUE TITLE
arc not complete for crossing dateline

### ISSUE THREAD

**Issue by xqin1** [springmeyer/arc.js#23] opened 2015-03-19 20:41 UTC
sample gist: https://gist.github.com/xqin1/b38dd6ed9ae96174b96e
two points for Seattle and Beijing, China. The arc seems to break at dateline, but the second half is not drawn.

**Comment by quantegy** [comment] 2016-04-26 17:51
I'm having the same issue. 

![Logbook Map](http://i.imgur.com/I8EIZ49.png)

Coordinates are [33.6442641, -117.8554282], [12.423, 123.514]

**Comment by mareg** [comment] 2017-07-25 20:59
Same issue here - trying to draw a flight path from LAX to SYD and I'm getting this:

![screenshot84](https://user-images.githubusercontent.com/533217/28593390-0a9d6122-7184-11e7-8f65-1d45afaf06d7.png)

```javascript
  var lax = [-33.946111, 151.177222];
  var syd = [33.9425, -118.408056];

  L.marker(lax).addTo(mymap);
  L.marker(syd).addTo(mymap);

  L.Polyline.Arc(syd, lax, {
    color: 'red',
    weight: 2,
    smoothFactor: 0.5,
    vertices: 20
  }).addTo(mymap);
```

**Comment by jgravois** [comment] 2024-08-15 16:56
nearly a decade has passed and i can't reproduce this on: https://springmeyer.github.io/arc.js/

![Screenshot 2024-08-15 at 9 55 58 AM](https://github.com/user-attachments/assets/c0dbe2b5-935b-4f7d-8e52-2059f5a055d7)

closing, but happy to discuss further, either here or in a new issue.

**Closed by jgravois** 2024-08-15 16:56 UTC
